const defaultDataReview = [
    {
      title: "Product 1",
      price: "10.99",
      description: "Lorem ipsum dolor sit amet",
      brand: "Brand 1",
      category: "Category 1",
      discount: "5",
      visibility: "public",
      postDate: "2023-07-01",
    },
    {
      title: "Product 2",
      price: "19.99",
      description: "Consectetur adipiscing elit",
      brand: "Brand 2",
      category: "Category 2",
      discount: "0",
      visibility: "private",
      postDate: "2023-07-02",
    },
    {
      title: "Product 3",
      price: "8.50",
      description: "Sed do eiusmod tempor incididunt",
      brand: "Brand 3",
      category: "Category 3",
      discount: "10",
      visibility: "partially-public",
      postDate: "2023-07-03",
    },
    {
      title: "Product 4",
      price: "12.75",
      description: "Ut enim ad minim veniam",
      brand: "Brand 1",
      category: "Category 2",
      discount: "15",
      visibility: "public",
      postDate: "2023-07-04",
    },
    {
      title: "Product 5",
      price: "14.99",
      description: "Duis aute irure dolor in reprehenderit",
      brand: "Brand 2",
      category: "Category 1",
      discount: "0",
      visibility: "private",
      postDate: "2023-07-05",
    },
    {
      title: "Product 6",
      price: "9.99",
      description: "Excepteur sint occaecat cupidatat non proident",
      brand: "Brand 3",
      category: "Category 3",
      discount: "20",
      visibility: "public",
      postDate: "2023-07-06",
    },
    {
      title: "Product 7",
      price: "7.49",
      description: "Sunt in culpa qui officia deserunt mollit",
      brand: "Brand 1",
      category: "Category 2",
      discount: "0",
      visibility: "private",
      postDate: "2023-07-07",
    },
    {
      title: "Product 8",
      price: "11.25",
      description: "Anim id est laborum",
      brand: "Brand 2",
      category: "Category 1",
      discount: "5",
      visibility: "partially-public",
      postDate: "2023-07-08",
    },
    {
      title: "Product 9",
      price: "16.99",
      description: "Nisi ut aliquip ex ea commodo consequat",
      brand: "Brand 3",
      category: "Category 3",
      discount: "0",
      visibility: "public",
      postDate: "2023-07-09",
    },
    {
      title: "Product 10",
      price: "13.50",
      description: "Duis aute irure dolor in reprehenderit",
      brand: "Brand 1",
      category: "Category 2",
      discount: "10",
      visibility: "private",
      postDate: "2023-07-10",
    },
  ];
  
  export default defaultDataReview;
  